api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views

urlpatterns = [
    path('user/', views.UserList.as_view(), name='register_or_get_details'),
    path('complaint/', views.ComplaintCreate.as_view(),
         name='new_or_all_complaints'),
    path('complaint/<int:pk>', views.ComplaintDetails.as_view(),
         name='complaint_details'),

    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path('', views.home, name='home')
]

complaints/urls.py
from django.urls import path
from . import views

app_name = 'complaints'
urlpatterns = [
    path('add-complaint', views.add_complaint, name='add-complaint'),
    path('update-complaint', views.update_complaint, name='update-complaint')
]

linear_depression/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('users.urls')),
    path('complaints/', include('complaints.urls')),
    path('api/', include('api.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.login_page, name='login-page'),
    path('signup-student', views.signup_student, name='signup-student'),
    path('signin-student', views.signin_student, name='signin-student'),
    path('signup-admin', views.signup_admin, name='signup-admin'),
    path('signin-admin', views.signin_admin, name='signin-admin'),
    path('logout', views.logout_page, name='logout-page')

]

api/models.py
from django.db import models

# Create your models here.

complaints/models.py
from django.db import models
from users.models import User

class Complaint(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=23)
    body = models.TextField()
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return self.category

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):

    WARDEN = 0
    STUDENT = 1

    role = models.SmallIntegerField(null=True)
    block = models.CharField(max_length=5)
    room = models.CharField(max_length=5, null=True)

api/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from complaints.serializer import ComplaintSerializer
from users.serializer import UserSerializer
from users.models import User
from complaints.models import Complaint


class UserList(generics.ListCreateAPIView):
    serializer_class = UserSerializer

    def get_queryset(self):
        return User.objects.filter(id=self.request.user.id)


class ComplaintCreate(generics.ListCreateAPIView):
    serializer_class = ComplaintSerializer
    permission_classes = [IsAuthenticated, ]

    def get_queryset(self):
        user = self.request.user
        complaints = Complaint.objects.filter(user=user)
        return complaints

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ComplaintDetails(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = ComplaintSerializer
    lookup_field = 'pk'
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Complaint.objects.filter(user=self.request.user)

    # Need check for role is it Admin or Student
    def perform_update(self, serializer):
        serializer.save(status=True)

base/views.py
from django.shortcuts import render, redirect
from complaints.models import Complaint

# Create your views here.


def home(req):
    if req.user.is_authenticated:
        if req.user.role:
            complaints = req.user.complaint_set.all()
        else:
            complaints = Complaint.objects.filter(
                user__block=req.user.username).filter(status=False)

        context = {'complaints': complaints}
        return render(req, 'base/home.html', context)
    return redirect('users:login-page')

complaints/views.py
from django.shortcuts import render, redirect
from .models import Complaint

# Create your views here.


def add_complaint(req):
    if req.method == 'POST':
        complaint = Complaint.objects.create(
            user=req.user,
            category=req.POST.get('complaint_type'),
            body=req.POST.get('complaint_text')
        )
        return redirect('base:home')

    return render(req, 'complaints/complaint.html')


def update_complaint(req):
    if req.method == 'POST':
        for id in req.POST.keys():
            try:
                complaint = Complaint.objects.get(id=id)
                complaint.status = True
                complaint.save()
            except:
                pass
        return redirect('base:home')

users/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def login_page(req):
    if req.user.is_authenticated:
        return redirect('base:home')
    return render(req, 'users/login.html')

def signup_student(req):
    if req.method == 'POST':
        user = User.objects.create_user(
            password=req.POST.get('student_password'),
            username=req.POST.get('student_id')
        )
        user.first_name = req.POST.get('student_name')
        user.block = req.POST.get('hostel_block')
        user.room = req.POST.get('room_number')
        user.email = req.POST.get('email')
        user.role = User.STUDENT
        user.save()
        login(req, user)
        return redirect('base:home')
    return render(req, 'users/login.html')


def signin_student(req):
    if req.method == 'POST':
        user = authenticate(req, username=req.POST.get('student_id'), password=req.POST.get('student_password'))
        if user is None:
            return redirect('users:login-page')
        login(req, user)
        return redirect('base:home')
    


def signup_admin(req):
    if req.method == 'POST':
        
        user = User.objects.create_user(
            password=req.POST.get('admin_password'),
            username=req.POST.get('admin_hostel')
        )
        user.first_name = req.POST.get('admin_name')
        user.email = req.POST.get('admin_email')
        user.role = User.WARDEN
        user.save()
        login(req, user)
        return redirect('base:home')
    return render(req, 'users/login.html')


def signin_admin(req):
    if req.method == 'POST':
        user = authenticate(req, username=req.POST.get('admin_hostel'), password=req.POST.get('admin_password'))
        if user is None:
            return redirect('users:login-page')
        login(req, user)
        return redirect('base:home')

def logout_page(req):
    logout(req)
    return render(req, 'users/login.html')

base/templates/base/admin_complaints_view.html
<main id="main">

  
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <form action="{% url 'complaints:update-complaint' %}" method="post">
        {% csrf_token %}
      <div class="container">
        <h2>Complaints Received</h2>
        <p class="text-end"><input class="btn btn-primary" type="submit" value="Save Changes "></p>
        <br><br>
        <div class="row">
          <table class="table table-hover" width="100%" cellspacing="40px" style="font-size:20px; text-align: center;">
            <tr class="table-light">
              <th>S No</th>
              <th>Complaint Type</th>
              <th>Description</th>
              <th>Status</th>
            </tr>
            
            {% for complaint in complaints %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><label for="{{ complaint.id }}">{{ complaint }}</label></td>
                <td><label for="{{ complaint.id }}">{{ complaint.body | slice:"0:10" }}...</label></td>
                <td>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="{{ complaint.id }}" name="{{ complaint.id }}" style="width: 1.5rem; height: 1.5rem;">

                  </div>
                </td>
              </tr>
            {% endfor %}
          </table>
          
        </div>

      </div>
    </form>
    </section><!-- End About Section -->

    <!-- ======= Counts Section ======= -->
    <section id="counts" class="counts">
      <div class="container">

        <div class="row counters">

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter">1</span>
            <h6>Total Complaints</h6>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter">2</span>
            <h6>Solved</h6>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1" class="purecounter">1</span>
            <h6>Under Progress</h6>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter">5</span>
            <h6>Unsolved</h6>
          </div>

        </div>

      </div>
    </section><!-- End Counts Section -->

    <!-- ======= Services Section ======= -->
    <section id="services" class="services section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Theme</h2>
          <p>The purpose of this webpage is to provide the students an interactive page to fill their comlpaints and keep a track of them.It also provides a track of previous complaints filed </p>
        </div>

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact section-bg">
      <div class="container" data-aos="fade-up">


        <div class="row">
          <div class="col-lg-6">
            <div class="info-box mb-4">
              <i class="bx bx-map"></i>
              <h3>Our Address</h3>
              <a>RGUKT RK Valley, Vempalli,Kadapa 516330</a>
            </div>
          </div>

          <div class="col-lg-6 col-md-6">
            <div class="info-box  mb-4">
              <i class="bx bx-envelope"></i>
              <h3>Website</h3>
              <a href="rgukt.in">rgukt.in</a>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

base/templates/base/dash.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Hostel Queries</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link rel="stylesheet" href="{% static 'styles/dash.css' %}">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="index.html">RGUKT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
        </li> -->

        <li class="nav-item active">
            <a class="nav-link" href="#hero">Dashboard<span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="#about">Your Complaints<span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:logout-page'  %}">Logout<span class="sr-only">(current)</span></a>
        </li>


    </ul>
      
    <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" id="c-status1" class="btn btn-warning">Student</button>
        <button type="button" id="c-status2"  class="btn btn-light">Administrator</button>
    </div>
  </nav>

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container-fluid" data-aos="fade-up">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 pt-3 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
          <h1>Welcome {{ user.first_name }} to Hostel Queries Dashboard</h1>
          <h2>Raise your complaints here by filling the form</h2>
          <div><a href="{% url 'complaints:add-complaint' %}" class="btn-get-started scrollto">Complaint</a></div>
        </div>
        <div class="col-xl-4 col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="150">
          <img src="assets/img/hero-img.png" class="img-fluid animated" alt="">
        </div>
      </div>
    </div>

  </section>

{% include 'base/student_complaints.html' %}

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-contact">
            <h3>Linear Depression</h3>
            <p>
              Boys Hostel<br>
              RK Valley-516330<br>
              Kadapa <br><br>
              <strong>Email:</strong><a href="mailto:rr200148@rguktrkv.ac.in" style="text-decoration:none;"> rr200148@rguktrkv.ac.in</a><br>
            </p>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Dashboard</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Complaints</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Contact Info</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Reach Us</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Machine Learning Models</a></li>
            </ul>
          </div>

    <div class="container">

    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

base/templates/base/home.html
{% extends 'main.html' %}



{% block content %}
{% if user.role %}
{% include 'base/dash.html' %}
{% else %}
{% include 'base/admin_dash.html' %}
{% endif %}

{% endblock %}

templates/heads.html
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/5.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
  crossorigin="anonymous"
/>
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/font-awesome/5.1/css/font-awesome.min.css"
  crossorigin="anonymous"
/>

<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
  crossorigin="anonymous"
/>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
  crossorigin="anonymous"
></script>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RGUKT</title>
    {% include "heads.html" %}
</head>
<body>

    {% block content %}
    {% endblock %}
    
    {% include "tails.html" %}
</body>
</html>

templates/tails.html
<script
src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
crossorigin="anonymous"
></script>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
crossorigin="anonymous"
></script>
<script
src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
crossorigin="anonymous"
></script>

users/templates/users/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    {% include "heads.html" %}
    <title>RGUKT</title>
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="index.html">RGUKT COMPLAINTS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <!-- <li class="nav-item active">
              <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
            </li> -->


        </ul>
          
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" id="c-status1" class="btn btn-warning">Student</button>
            <button type="button" id="c-status2"  class="btn btn-light">Administrator</button>
        </div>
      </nav>

      <!-- sign up-in -->
      <section class="h-100 gradient-form" id="sec1" style="background-color: #eee;">
        <div class="container py-4 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
              <div class="card rounded-3 text-black">
                <div class="row g-0">
                  <div class="col-lg-6">

                    <div class="card-body p-md-5 mx-md-6">
      
                      <div class="text-center">
                        <!-- <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                          style="width: 185px;" alt="logo"> -->
                        <h4 class="mt-1 mb-5 pb-1">Sign In</h4>
                      </div>
      
                      <form action="{% url 'users:signin-student' %}" method="post">
                        {% csrf_token %}
                        <p>Please Sign In to continue</p>
      
                        <div class="form-outline mb-4">
                            <label class="form-label" for="form2Example11">RGUKT ID</label>
                            <input type="text" id="form2Example11" class="form-control" name="student_id"
                                placeholder="R20XXXX" pattern="R[0-9]{6}"/>
                        </div>
      
                        <div class="form-outline mb-4">
                            <label class="form-label" for="form2Example22">Password</label>
                            <input type="password" id="form2Example22" class="form-control" name="student_password" placeholder="Enter your password"/>
                        </div>
      
                        <div class="text-center pt-1 mb-5 pb-1">
                          <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Sign In</button>
                          <a class="text-muted" href="#!">Forgot password?</a>
                        </div>
      
                      </form>
      
                    </div>
                  </div>


                  <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                    <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                        <div class="text-center">
                            <!-- <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                              style="width: 185px;" alt="logo"> -->
                            <h4 class="mt-1 mb-5 pb-1">Sign Up</h4>
                          </div>
          
                          <form action="{% url 'users:signup-student' %}" method="post">
                            {% csrf_token %}
                            <p>Please Sign Up to continue</p>
                        
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="name">Name</label>
                                    <input type="text" id="name" class="form-control" name="student_name" placeholder="Your Name">
                                </div>
                        
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="id">ID No</label>
                                    <input type="text" id="id" class="form-control" name="student_id" placeholder="R2XXXXX" pattern="R[0-9]{6}">
                                </div>
                            </div>
                        
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="password">Password</label>
                                    <input type="password" id="password" class="form-control" name="student_password" placeholder="Create Password">
                                </div>
                        
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="room">Room No</label>
                                    <input type="text" id="room" class="form-control" name="room_number" placeholder="X-XXX">
                                </div>
                            </div>
                        
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="block">Hostel Block</label>
                                    <select class="form-control" name="hostel_block">
                                      <option>BH-1 </option>
                                      <option>BH-2 </option>
                                      <option>GH-1 </option>
                                      <option>GH-2 </option>
                                    </select>
                                </div>
                        
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="email">Email</label>
                                    <input type="email" id="email" class="form-control" name="email" placeholder="Your Email">
                                </div>
                            </div>
                        
                            <div class="text-center pt-1 mb-5 pb-1">
                                <button class="btn btn-primary btn-block fa-lg gradient-custom-3 mb-3" type="submit">Sign Up</button>
                                
                            </div>
                        </form>
                        
          
                        </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

      <section class="h-100 gradient-form" id="sec2" style="background-color: #eee;">
        <div class="container py-4 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
              <div class="card rounded-3 text-black">
                <div class="row g-0">
                  <div class="col-lg-6">

                    <div class="card-body p-md-5 mx-md-6">
      
                      <div class="text-center">

                        <h4 class="mt-1 mb-5 pb-1">Sign In </h4>
                      </div>
      
                      <form action="{% url 'users:signin-admin' %}" method="post">
                        {% csrf_token %}
                        <p>Please Sign In to continue</p>
      
                        <div class="form-outline mb-4">
                          <div class="col-md-6 mb-4">
                            <label class="form-label" for="block">Hostel Block</label>
                            <select class="form-control" name="admin_hostel">
                              <option>BH-1 </option>
                              <option>BH-2 </option>
                              <option>GH-1 </option>
                              <option>GH-2 </option>
                            </select>
                        </div>
                        </div>
      
                        <div class="form-outline mb-4">
                            <label class="form-label" for="2form2Example22">Password</label>
                            <input type="password" id="2form2Example22" class="form-control" name="admin_password" placeholder="Enter your password"/>
                        </div>
      
                        <div class="text-center pt-1 mb-5 pb-1">
                          <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Sign In</button>
                          <a class="text-muted" href="#!">Forgot password?</a>
                        </div>
      
                      </form>
      
                    </div>
                  </div>


                  <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                    <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                        <div class="text-center">
                           
                            <h4 class="mt-1 mb-5 pb-1">Sign Up</h4>
                          </div>
          
                          <form action="{% url 'users:signup-admin' %}" method="post">
                            {% csrf_token %}
                            <p>Please Sign Up to continue</p>
                        
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="2name">Name</label>
                                    <input type="text" id="2name" class="form-control" name="admin_name" placeholder="Your Name">
                                </div>
                        
                                <div class="col-md-6 mb-4">
                                  <label class="form-label" for="block">Hostel Block</label>
                                  <select class="form-control" name="admin_hostel">
                                    <option>BH-1 </option>
                                    <option>BH-2 </option>
                                    <option>GH-1 </option>
                                    <option>GH-2 </option>
                                  </select>
                              </div>
                            </div>
                        
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                 <label class="form-label" for="2room">Email Id</label>
                                  <input type="text" id="2room" class="form-control" name="admin_email" placeholder="Email-id">
                                </div>
                                <div class="col-md-6 mb-4">
                                    <label class="form-label" for="2password">Password</label>
                                    <input type="password" id="2password" class="form-control" name="admin_password" placeholder="Create Password">
                                </div>
                        
                              </div>

                            <div class="text-center pt-1 mb-5 pb-1">
                                <button class="btn btn-primary btn-block fa-lg gradient-custom-3 mb-3" type="submit">Sign Up</button>
                                <!-- <a class="text-muted" href="#!">Forgot password?</a> -->
                            </div>
                        </form>
                        
          
                        </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% include "tails.html" %}

</body>
</html>